# Generated by Django 3.1 on 2021-04-28 19:14

import dirtyfields.dirtyfields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import rules.contrib.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID')),
                ('filehash', models.CharField(editable=False, max_length=65,
                    verbose_name='Title')),
                ('mimetype', models.CharField(editable=False, max_length=50,
                    verbose_name='Mime Type')),
                ('description', models.TextField(verbose_name='Description')),
                ('description_ind', models.TextField(null=True,
                    verbose_name='Description')),
                ('description_en', models.TextField(null=True,
                    verbose_name='Description')),
                ('alt_text', models.TextField(blank=True, null=True,
                    verbose_name='Alternate Text')),
                ('alt_text_ind', models.TextField(blank=True, null=True,
                    verbose_name='Alternate Text')),
                ('alt_text_en', models.TextField(blank=True, null=True,
                    verbose_name='Alternate Text')),
                ('databits', models.FileField(blank=True, null=True,
                    upload_to='files/original/', verbose_name='Content')),
                ('image', models.ImageField(blank=True,
                    height_field='image_height', null=True,
                    upload_to='files/original/', verbose_name='Image',
                    width_field='image_width')),
                ('image_height', models.SmallIntegerField(editable=False,
                    null=True)),
                ('image_width', models.SmallIntegerField(editable=False,
                    null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True,
                    null=True)),
                ('image_xs', models.ImageField(editable=False, null=True,
                    upload_to='files/image_xs/')),
                ('image_sm', models.ImageField(editable=False, null=True,
                    upload_to='files/image_sm/')),
                ('image_md', models.ImageField(editable=False, null=True,
                    upload_to='files/image_md/')),
                ('image_lg', models.ImageField(editable=False, null=True,
                    upload_to='files/image_lg/')),
                ('created_by', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='created_file', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin,
                    rules.contrib.models.RulesModelMixin, models.Model),
        ),
    ]
