# Generated by Django 4.0.4 on 2022-04-20 05:03
# pylint:disable=line-too-long,missing-module-docstring,missing-class-docstring

import dirtyfields.dirtyfields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import rules.contrib.models
import website.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filehash', models.CharField(editable=False, max_length=65, verbose_name='Title')),
                ('mimetype', models.CharField(editable=False, max_length=50, verbose_name='Mime Type')),
                ('description_id', models.TextField(verbose_name='Description')),
                ('description_en', models.TextField(blank=True, verbose_name='Description')),
                ('description_su', models.TextField(blank=True, verbose_name='Description')),
                ('description_jv', models.TextField(blank=True, verbose_name='Description')),
                ('alt_text_id', models.TextField(blank=True, help_text='Only need to fill this if you were uploading an image.', null=True, verbose_name='Alternate Text (alt text)')),
                ('alt_text_en', models.TextField(blank=True, help_text='Only need to fill this if you were uploading an image.', null=True, verbose_name='Alternate Text (alt text)')),
                ('alt_text_su', models.TextField(blank=True, help_text='Only need to fill this if you were uploading an image.', null=True, verbose_name='Alternate Text (alt text)')),
                ('alt_text_jv', models.TextField(blank=True, help_text='Only need to fill this if you were uploading an image.', null=True, verbose_name='Alternate Text (alt text)')),
                ('databits', models.FileField(upload_to='files/original/', verbose_name='Content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('image_xs', models.ImageField(editable=False, null=True, upload_to='files/image_xs/')),
                ('image_sm', models.ImageField(editable=False, null=True, upload_to='files/image_sm/')),
                ('image_md', models.ImageField(editable=False, null=True, upload_to='files/image_md/')),
                ('image_lg', models.ImageField(editable=False, null=True, upload_to='files/image_lg/')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, website.mixins.MultilingualMixin, rules.contrib.models.RulesModelMixin, models.Model),
        ),
    ]
