# Generated by Django 4.2 on 2023-04-10 23:18
# pylint:disable=line-too-long,missing-module-docstring,missing-class-docstring

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfile',
            name='alt_text_en',
            field=models.TextField(blank=True, help_text='Textual representation of media or hyperlink text.', null=True, verbose_name='Alternate Text (alt text)'),
        ),
        migrations.AlterField(
            model_name='myfile',
            name='alt_text_id',
            field=models.TextField(help_text='Textual representation of media or hyperlink text.', null=True, verbose_name='Alternate Text (alt text)'),
        ),
        migrations.AlterField(
            model_name='myfile',
            name='alt_text_jv',
            field=models.TextField(blank=True, help_text='Textual representation of media or hyperlink text.', null=True, verbose_name='Alternate Text (alt text)'),
        ),
        migrations.AlterField(
            model_name='myfile',
            name='alt_text_su',
            field=models.TextField(blank=True, help_text='Textual representation of media or hyperlink text.', null=True, verbose_name='Alternate Text (alt text)'),
        ),
        migrations.AlterField(
            model_name='myfile',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='myfile',
            name='description_id',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='myfile',
            name='description_jv',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='myfile',
            name='description_su',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
