# Generated by Django 3.1 on 2021-06-27 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfile',
            name='alt_text',
            field=models.TextField(blank=True,
                help_text='Only need to fill this if you were uploading an image.', # pylint:disable=line-too-long
                null=True, verbose_name='Alternate Text (alt text)'),
        ),
        migrations.AlterField(
            model_name='myfile',
            name='alt_text_en',
            field=models.TextField(blank=True,
                help_text='Only need to fill this if you were uploading an image.', # pylint:disable=line-too-long
                null=True, verbose_name='Alternate Text (alt text)'),
        ),
        migrations.AlterField(
            model_name='myfile',
            name='alt_text_ind',
            field=models.TextField(blank=True,
                help_text='Only need to fill this if you were uploading an image.', # pylint:disable=line-too-long
                null=True, verbose_name='Alternate Text (alt text)'),
        ),
    ]
