# Generated by Django 4.2 on 2023-04-11 05:28
# pylint:disable=line-too-long,missing-module-docstring,missing-class-docstring

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_files', '0002_alter_myfile_alt_text_en_alter_myfile_alt_text_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myfile',
            name='image_xlg',
            field=models.ImageField(editable=False, null=True, upload_to='files/image_xlg/'),
        ),
    ]
