# Generated by Django 3.1 on 2022-04-15 15:23
# pylint:disable=line-too-long

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_files', '0004_auto_20220122_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='myfile',
            name='alt_text_jv',
            field=models.TextField(blank=True,
                help_text='Only need to fill this if you were uploading an image.',
                null=True, verbose_name='Alternate Text (alt text)'),
        ),
        migrations.AddField(
            model_name='myfile',
            name='alt_text_su',
            field=models.TextField(blank=True,
                help_text='Only need to fill this if you were uploading an image.',
                null=True, verbose_name='Alternate Text (alt text)'),
        ),
        migrations.AddField(
            model_name='myfile',
            name='description_jv',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='myfile',
            name='description_su',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
    ]
