# Generated by Django 3.1 on 2022-01-22 16:48

import dirtyfields.dirtyfields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import rules.contrib.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_files', '0004_auto_20220122_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='MySlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('front', 'Front Page')],
                    db_index=True, max_length=12, verbose_name='Location')),
                ('description', models.TextField(verbose_name='Description')),
                ('description_ind', models.TextField(null=True,
                    verbose_name='Description')),
                ('description_en', models.TextField(null=True,
                    verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='created_slides',
                    to=settings.AUTH_USER_MODEL)),
                ('image', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='my_files.myfile', verbose_name='Image')),
            ],
            options={
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin,
                rules.contrib.models.RulesModelMixin, models.Model),
        ),
    ]
