# Generated by Django 4.0.4 on 2022-04-20 05:03
# pylint:disable=line-too-long,missing-module-docstring,missing-class-docstring

import dirtyfields.dirtyfields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import rules.contrib.models
import website.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('my_files', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MySlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('front', 'Front Page')], db_index=True, max_length=12, verbose_name='Location')),
                ('position', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Position')),
                ('description_id', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_su', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_jv', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_slides', to=settings.AUTH_USER_MODEL)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_files.myfile', verbose_name='Image')),
            ],
            options={
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, website.mixins.MultilingualMixin, rules.contrib.models.RulesModelMixin, models.Model),
        ),
    ]
