# Generated by Django 3.1 on 2022-02-07 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_slide', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myslide',
            name='description',
            field=models.TextField(blank=True, null=True,
                verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='myslide',
            name='description_en',
            field=models.TextField(blank=True, null=True,
                verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='myslide',
            name='description_ind',
            field=models.TextField(blank=True, null=True,
                verbose_name='Description'),
        ),
    ]
