# Generated by Django 3.1 on 2022-04-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_slide', '0003_myslide_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='myslide',
            name='description_jv',
            field=models.TextField(blank=True, null=True,
                verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='myslide',
            name='description_su',
            field=models.TextField(blank=True, null=True,
                verbose_name='Description'),
        ),
    ]
