# Generated by Django 3.1 on 2022-03-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_front_content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontcontent',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0,
                verbose_name='Position'),
        ),
    ]
