# Generated by Django 3.1.7 on 2021-02-25 05:25

import dirtyfields.dirtyfields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import rules.contrib.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPosting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=65)),
                ('body', models.TextField()),
                ('summary', models.TextField(max_length=155)),
                ('slug', models.SlugField(blank=True,
                    help_text='Human friendly unique url to identify the content, will automatically be filled if left empty.', # pylint:disable=line-too-long
                    max_length=64, unique=True)),
                ('image', models.ImageField(blank=True,
                    height_field='image_height', null=True,
                    upload_to='blog_posting/original/',
                    width_field='image_width')),
                ('image_height', models.SmallIntegerField(editable=False,
                    null=True)),
                ('image_width', models.SmallIntegerField(editable=False,
                    null=True)),
                ('cover', models.ImageField(editable=False, null=True,
                    upload_to='blog_posting/cover/')),
                ('published_at', models.DateTimeField(blank=True, db_index=True,
                    null=True, verbose_name='publish date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True,
                    null=True)),
                ('created_by', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='created_blogpostings',
                    to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='published_blogpostings',
                    to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-modified_at'],
                'get_latest_by': 'published_at',
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin,
                rules.contrib.models.RulesModelMixin, models.Model),
        ),
    ]
