# Generated by Django 4.2 on 2023-04-07 11:51
# pylint:disable=line-too-long,missing-module-docstring,missing-class-docstring

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_posting', '0002_blogposting_image_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogposting',
            name='image',
        ),
        migrations.RemoveField(
            model_name='blogposting',
            name='image_height',
        ),
        migrations.RemoveField(
            model_name='blogposting',
            name='image_lg',
        ),
        migrations.RemoveField(
            model_name='blogposting',
            name='image_md',
        ),
        migrations.RemoveField(
            model_name='blogposting',
            name='image_sm',
        ),
        migrations.RemoveField(
            model_name='blogposting',
            name='image_width',
        ),
        migrations.RemoveField(
            model_name='blogposting',
            name='image_xs',
        ),
    ]
