# Generated by Django 3.1.7 on 2021-03-13 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_posting', '0002_auto_20210225_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogposting',
            name='cover',
        ),
        migrations.AddField(
            model_name='blogposting',
            name='image_lg',
            field=models.ImageField(editable=False, null=True,
                upload_to='blog_posting/image_lg/'),
        ),
        migrations.AddField(
            model_name='blogposting',
            name='image_md',
            field=models.ImageField(editable=False, null=True,
                upload_to='blog_posting/image_md/'),
        ),
        migrations.AddField(
            model_name='blogposting',
            name='image_sm',
            field=models.ImageField(editable=False, null=True,
                upload_to='blog_posting/image_sm/'),
        ),
        migrations.AddField(
            model_name='blogposting',
            name='image_xs',
            field=models.ImageField(editable=False, null=True,
                upload_to='blog_posting/image_xs/'),
        ),
    ]
