# Generated by Django 3.1 on 2021-04-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_posting', '0003_auto_20210313_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogposting',
            name='body',
            field=models.TextField(verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='blogposting',
            name='body_en',
            field=models.TextField(null=True, verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='blogposting',
            name='body_ind',
            field=models.TextField(null=True, verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='blogposting',
            name='image',
            field=models.ImageField(blank=True, height_field='image_height',
                null=True, upload_to='blog_posting/original/',
                verbose_name='Image', width_field='image_width'),
        ),
        migrations.AlterField(
            model_name='blogposting',
            name='published_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True,
                verbose_name='Publish Date'),
        ),
        migrations.AlterField(
            model_name='blogposting',
            name='summary',
            field=models.TextField(max_length=155, verbose_name='Summary'),
        ),
        migrations.AlterField(
            model_name='blogposting',
            name='summary_en',
            field=models.TextField(max_length=155, null=True,
                verbose_name='Summary'),
        ),
        migrations.AlterField(
            model_name='blogposting',
            name='summary_ind',
            field=models.TextField(max_length=155, null=True,
                verbose_name='Summary'),
        ),
        migrations.AlterField(
            model_name='blogposting',
            name='title',
            field=models.CharField(max_length=65, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='blogposting',
            name='title_en',
            field=models.CharField(max_length=65, null=True,
                verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='blogposting',
            name='title_ind',
            field=models.CharField(max_length=65, null=True,
                verbose_name='Title'),
        ),
    ]
