# Generated by Django 3.1 on 2022-01-17 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_posting', '0004_auto_20210417_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogposting',
            name='slug',
            field=models.SlugField(blank=True,
                help_text='Human friendly unique url to identify the content, will automatically be filled if left empty.', # pylint:disable=line-too-long
                max_length=64, unique=True, verbose_name='URL Name'),
        ),
        migrations.AlterField(
            model_name='blogposting',
            name='slug_en',
            field=models.SlugField(blank=True,
                help_text='Human friendly unique url to identify the content, will automatically be filled if left empty.', # pylint:disable=line-too-long
                max_length=64, null=True, unique=True, verbose_name='URL Name'),
        ),
        migrations.AlterField(
            model_name='blogposting',
            name='slug_ind',
            field=models.SlugField(blank=True,
                help_text='Human friendly unique url to identify the content, will automatically be filled if left empty.', # pylint:disable=line-too-long
                max_length=64, null=True, unique=True, verbose_name='URL Name'),
        ),
    ]
