# Generated by Django 4.2 on 2023-04-08 01:43
# pylint:disable=line-too-long,missing-module-docstring,missing-class-docstring

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_posting', '0004_rename_image_new_blogposting_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogposting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='blogposting',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
