# Generated by Django 3.1 on 2022-04-15 15:23
# pylint:disable=line-too-long

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_posting', '0005_auto_20220117_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogposting',
            name='body_jv',
            field=models.TextField(null=True, verbose_name='Body'),
        ),
        migrations.AddField(
            model_name='blogposting',
            name='body_su',
            field=models.TextField(null=True, verbose_name='Body'),
        ),
        migrations.AddField(
            model_name='blogposting',
            name='slug_jv',
            field=models.SlugField(blank=True,
                help_text='Human friendly unique url to identify the content, will automatically be filled if left empty.',
                max_length=64, null=True, unique=True, verbose_name='URL Name'),
        ),
        migrations.AddField(
            model_name='blogposting',
            name='slug_su',
            field=models.SlugField(blank=True,
                help_text='Human friendly unique url to identify the content, will automatically be filled if left empty.',
                max_length=64, null=True, unique=True, verbose_name='URL Name'),
        ),
        migrations.AddField(
            model_name='blogposting',
            name='summary_jv',
            field=models.TextField(max_length=155, null=True,
                verbose_name='Summary'),
        ),
        migrations.AddField(
            model_name='blogposting',
            name='summary_su',
            field=models.TextField(max_length=155, null=True,
                verbose_name='Summary'),
        ),
        migrations.AddField(
            model_name='blogposting',
            name='title_jv',
            field=models.CharField(max_length=65, null=True,
                verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='blogposting',
            name='title_su',
            field=models.CharField(max_length=65, null=True,
                verbose_name='Title'),
        ),
    ]
