# Generated by Django 4.2 on 2023-04-10 02:33
# pylint:disable=line-too-long,missing-module-docstring,missing-class-docstring

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_files', '0001_initial'),
        ('blog_posting', '0005_alter_blogposting_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogposting',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_files.myfile', verbose_name='Image'),
        ),
    ]
