# Generated by Django 3.1 on 2022-01-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage',
            name='slug',
            field=models.SlugField(blank=True,
                help_text='Human friendly unique url to identify the content, will automatically be filled if left empty.', # pylint:disable=line-too-long
                max_length=64, unique=True, verbose_name='URL Name'),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='slug_en',
            field=models.SlugField(blank=True,
                help_text='Human friendly unique url to identify the content, will automatically be filled if left empty.', # pylint:disable=line-too-long
                max_length=64, null=True, unique=True, verbose_name='URL Name'),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='slug_ind',
            field=models.SlugField(blank=True,
                help_text='Human friendly unique url to identify the content, will automatically be filled if left empty.', # pylint:disable=line-too-long
                max_length=64, null=True, unique=True, verbose_name='URL Name'),
        ),
    ]
