# Generated by Django 3.1 on 2022-02-28 18:02

import dirtyfields.dirtyfields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import rules.contrib.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(db_index=True,
                    verbose_name='Started At')),
                ('stopped_at', models.DateTimeField(blank=True, db_index=True,
                    null=True, verbose_name='Stopped At')),
                ('title', models.CharField(max_length=65,
                    verbose_name='Title')),
                ('title_ind', models.CharField(max_length=65, null=True,
                    verbose_name='Title')),
                ('title_en', models.CharField(max_length=65, null=True,
                    verbose_name='Title')),
                ('body', models.TextField(verbose_name='Body')),
                ('body_ind', models.TextField(null=True, verbose_name='Body')),
                ('body_en', models.TextField(null=True, verbose_name='Body')),
                ('summary', models.TextField(verbose_name='Summary')),
                ('summary_ind', models.TextField(null=True,
                    verbose_name='Summary')),
                ('summary_en', models.TextField(null=True,
                    verbose_name='Summary')),
                ('slug', models.SlugField(blank=True,
                    help_text='Human friendly unique url to identify the content, will automatically be filled if left empty.', # pylint:disable=line-too-long
                    max_length=64, unique=True, verbose_name='URL Name')),
                ('slug_ind', models.SlugField(blank=True,
                    help_text='Human friendly unique url to identify the content, will automatically be filled if left empty.', # pylint:disable=line-too-long
                    max_length=64, null=True, unique=True,
                    verbose_name='URL Name')),
                ('slug_en', models.SlugField(blank=True,
                    help_text='Human friendly unique url to identify the content, will automatically be filled if left empty.', # pylint:disable=line-too-long
                    max_length=64, null=True, unique=True,
                    verbose_name='URL Name')),
                ('published_at', models.DateTimeField(blank=True, db_index=True,
                    null=True, verbose_name='Publish Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True,
                    null=True)),
                ('created_by', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='created_events',
                    to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='published_events',
                    to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin,
                    rules.contrib.models.RulesModelMixin, models.Model),
        ),
    ]
