# Generated by Django 4.2 on 2023-04-08 05:44
# pylint:disable=line-too-long,missing-module-docstring,missing-class-docstring

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_event', '0002_alter_event_body_id_alter_event_summary_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='body_en',
            field=models.TextField(blank=True, null=True, verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='event',
            name='body_id',
            field=models.TextField(blank=True, null=True, verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='event',
            name='body_jv',
            field=models.TextField(blank=True, null=True, verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='event',
            name='body_su',
            field=models.TextField(blank=True, null=True, verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug_en',
            field=models.SlugField(blank=True, help_text='Human friendly unique url to identify the content, will automatically be filled if left empty.', max_length=64, null=True, unique=True, verbose_name='URL Name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug_jv',
            field=models.SlugField(blank=True, help_text='Human friendly unique url to identify the content, will automatically be filled if left empty.', max_length=64, null=True, unique=True, verbose_name='URL Name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug_su',
            field=models.SlugField(blank=True, help_text='Human friendly unique url to identify the content, will automatically be filled if left empty.', max_length=64, null=True, unique=True, verbose_name='URL Name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='summary_en',
            field=models.TextField(blank=True, null=True, verbose_name='Summary'),
        ),
        migrations.AlterField(
            model_name='event',
            name='summary_id',
            field=models.TextField(blank=True, null=True, verbose_name='Summary'),
        ),
        migrations.AlterField(
            model_name='event',
            name='summary_jv',
            field=models.TextField(blank=True, null=True, verbose_name='Summary'),
        ),
        migrations.AlterField(
            model_name='event',
            name='summary_su',
            field=models.TextField(blank=True, null=True, verbose_name='Summary'),
        ),
    ]
